version: '3'

services:
  enceladus_backend:
    image: felixenceladus/enceladus_backend:latest
    container_name: enceladus_backend
    restart: unless-stopped
    networks:
      - app-network

  enceladus_gateway:
    image: nginx:mainline-alpine
    container_name: enceladus_gateway
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./dist:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - enceladus_backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
